---
title: "Taxon log-ratio analysis"
author: Johannes Björk
output: html_notebook
---

```{r, echo=T, eval=T, message=FALSE, warning=FALSE}
library(phyloseq)
library(compositions)
library(tidyverse)
library(patchwork)
library(RColorBrewer)
```

```{r, echo=T, eval=T, message=FALSE, warning=FALSE}
# Prepare data for phylum level log-ratios

# Read-in and agglomerate data
ps <- readRDS("ps.RDS") %>% 
  tax_glom("phylum")

metadata <- as(sample_data(ps), "data.frame")
ftbl <- as(otu_table(ps),"matrix") 
tax <- data.frame(as(tax_table(ps),"matrix")) 
colnames(ftbl) <- tax$phylum

# Filter metadata to the best-sampled animals
# We initially filtered to the best-sampled 75 host animals, but shortly thereafter decided to removed less densely sampled time periods to improve the fitting of the GAMs. This resulted in 56 host animals (Fig. S2) 
metadata_filtered <- as(sample_data(ps), "data.frame") %>%
    select(sample_id, host, grp, collection_date, month, hydro_year, season) %>% 
    group_by(host) %>% 
    mutate(host=as.character(host),
           grp=as.character(grp),
           n_samples=n()) %>% 
    ungroup() %>% 
    arrange(desc(n_samples)) %>% 
    filter(n_samples >= 75,
           collection_date >= "2002-01-01",
           collection_date < "2010-01-01")

# For all time-dependent analyses except from the GAMs, we average samples (read counts) collected from the same host in the group sampled the same date
index <- as.integer(factor(paste0(metadata$host, "_", metadata$grp, "_", metadata$collection_date)))
ftbl_avg <- data.frame(ftbl, index)
ftbl_avg <- as.matrix(aggregate(.~index, ftbl_avg, mean))
metadata_avg <- cbind(data.frame(metadata[,c("sample_id","collection_date","season","hydro_year","month", "grp", "host")]),
                       data.frame(index=index))
rownames(ftbl_avg) <- metadata_avg[!duplicated(index),]$sample_id
metadata_avg <- metadata_avg[metadata_avg$sample_id %in% rownames(ftbl_avg),]
ftbl_avg <- subset(ftbl_avg, select=-index)
ftbl_avg <- ftbl_avg[,colSums(ftbl_avg)>0]
ftbl_avg <- ceiling(ftbl_avg)

# 0 imputation and clr-transformation
ftbl_avg_imp <- ftbl_avg
ftbl_avg_imp[ftbl_avg_imp<0.0001] <- 0.65
ftbl_avg_clr <- compositions::clr(ftbl_avg_imp)
```

```{r, echo=T, eval=T, message=FALSE, warning=FALSE}
# Taxon log-ratios aggregated over time
features <- data.frame(feature=colnames(ftbl_avg_clr))
log_ratios_host_phy <- vector("list", length(unique(metadata_filtered$host)))
names(log_ratios_host_phy) <- unique(metadata_filtered$host)
log_ratios_host_phy <- lapply(log_ratios_host_phy, function(x) cbind(features, log_ratio=NA, taxon_level="phylum"))

std <- function(x) sd(x)/sqrt(length(x))

for(host in unique(metadata_filtered$host)) {
  
  focal_metadata <- metadata_avg[metadata_avg$host %in% host,][,c("sample_id","host","collection_date")]
  
  for(row in 1:nrow(features)) {
    log_ratios_host_phy[[host]][row,]$log_ratio <- mean(ftbl_avg_clr[focal_metadata$sample_id, features$feature[row]], na.rm=T) - mean(ftbl_avg_clr[, features$feature[row]], na.rm=T)
  }
}

# Taxon log-ratios for each season and hydrological year
year_season <- sort(c(paste0(unique(metadata_filtered$hydro_year),"_", "aWet"),
                      paste0(unique(metadata_filtered$hydro_year),"_", "bDry")))
year_season <- gsub(year_season, pattern="a", replacement="")
year_season <- gsub(year_season, pattern="b", replacement="")

year_season_hosts <- crossing(year_season, hosts=gtools::mixedsort(unique(as.character(metadata_filtered$host))))

log_ratios_year_season_host_phy <- vector("list", nrow(year_season_hosts))
names(log_ratios_year_season_host_phy) <- paste0(year_season_hosts$year_season,"_",year_season_hosts$hosts)
log_ratios_year_season_host_phy <- lapply(log_ratios_year_season_host_phy, function(x) cbind(features, log_ratio=NA, log_ratio_std=NA))

for(year_season_host in names(log_ratios_year_season_host_phy)) {
  focal_metadata <- metadata_avg[metadata_avg$hydro_year %in% str_split(year_season_host, "\\_", simplify=T)[,1] & metadata_avg$season %in% str_split(year_season_host, "\\_", simplify=T)[,2] & metadata_avg$host %in% paste(str_split(year_season_host, "\\_", simplify=T)[,3:4], collapse="_"),][,c("sample_id","host","collection_date","hydro_year","season")]
  for(row in 1:nrow(features)) {
    
    log_ratios_year_season_host_phy[[year_season_host]][row,]$log_ratio <- mean(ftbl_avg_clr[focal_metadata$sample_id, features$feature[row]],na.rm=T) - mean(ftbl_avg_clr[, features$feature[row]], na.rm=T)
    log_ratios_year_season_host_phy[[year_season_host]][row,]$log_ratio_std <- std(ftbl_avg_clr[focal_metadata$sample_id, features$feature[row]])-std(ftbl_avg_clr[,features$feature[row]])
  }
}
```


```{r, echo=T, eval=T, message=FALSE, warning=FALSE}
# Prepare data for family level log-ratios

# Read-in and agglomerate data
ps <- readRDS("ps.RDS") %>% 
  tax_glom("family")

metadata <- as(sample_data(ps), "data.frame")
ftbl <- as(otu_table(ps),"matrix") 
tax <- data.frame(as(tax_table(ps),"matrix")) 
colnames(ftbl) <- tax$family

# Filter metadata to the best-sampled animals
# We initially filtered to the best-sampled 75 host animals, but shortly thereafter decided to removed less densely sampled time periods to improve the fitting of the GAMs. This resulted in 56 host animals (Fig. S2) 
metadata_filtered <- as(sample_data(ps), "data.frame") %>%
    select(sample_id, host, grp, collection_date, month, hydro_year, season) %>% 
    group_by(host) %>% 
    mutate(host=as.character(host),
           grp=as.character(grp),
           n_samples=n()) %>% 
    ungroup() %>% 
    arrange(desc(n_samples)) %>% 
    filter(n_samples >= 75,
           collection_date >= "2002-01-01",
           collection_date < "2010-01-01")

# For all time-dependent analyses except from the GAMs, we average samples (read counts) collected from the same host in the group sampled the same date
index <- as.integer(factor(paste0(metadata$host, "_", metadata$grp, "_", metadata$collection_date)))
ftbl_avg <- data.frame(ftbl, index)
ftbl_avg <- as.matrix(aggregate(.~index, ftbl_avg, mean))
metadata_avg <- cbind(data.frame(metadata[,c("sample_id","collection_date","season","hydro_year","month", "grp", "host")]),
                       data.frame(index=index))
rownames(ftbl_avg) <- metadata_avg[!duplicated(index),]$sample_id
metadata_avg <- metadata_avg[metadata_avg$sample_id %in% rownames(ftbl_avg),]
ftbl_avg <- subset(ftbl_avg, select=-index)
ftbl_avg <- ftbl_avg[,colSums(ftbl_avg)>0]
ftbl_avg <- ceiling(ftbl_avg)

# 0 imputation and clr-transformation
ftbl_avg_imp <- ftbl_avg
ftbl_avg_imp[ftbl_avg_imp<0.0001] <- 0.65
ftbl_avg_clr <- compositions::clr(ftbl_avg_imp)
```

```{r, echo=T, eval=T, message=FALSE, warning=FALSE}
# Taxon log-ratios aggregated over time

features <- data.frame(feature=colnames(ftbl_avg_clr))
log_ratios_host_fam <- vector("list", length(unique(metadata_filtered$host)))
names(log_ratios_host_fam) <- unique(metadata_filtered$host)
log_ratios_host_fam <- lapply(log_ratios_host_fam, function(x) cbind(features, log_ratio=NA, taxon_level="family"))

std <- function(x) sd(x)/sqrt(length(x))

for(host in unique(metadata_filtered$host)) {
  
  focal_metadata <- metadata_avg[metadata_avg$host %in% host,][,c("sample_id","host","collection_date")]
  
  for(row in 1:nrow(features)) {
    log_ratios_host_fam[[host]][row,]$log_ratio <- mean(ftbl_avg_clr[focal_metadata$sample_id, features$feature[row]], na.rm=T) - mean(ftbl_avg_clr[, features$feature[row]], na.rm=T)
  }
}

# Taxon log-ratios for each season and hydrological year
year_season <- sort(c(paste0(unique(metadata_filtered$hydro_year),"_", "aWet"),
                      paste0(unique(metadata_filtered$hydro_year),"_", "bDry")))
year_season <- gsub(year_season, pattern="a", replacement="")
year_season <- gsub(year_season, pattern="b", replacement="")

year_season_hosts <- crossing(year_season, hosts=gtools::mixedsort(unique(as.character(metadata_filtered$host))))

log_ratios_year_season_host_fam <- vector("list", nrow(year_season_hosts))
names(log_ratios_year_season_host_fam) <- paste0(year_season_hosts$year_season,"_",year_season_hosts$hosts)
log_ratios_year_season_host_fam <- lapply(log_ratios_year_season_host_fam, function(x) cbind(features, log_ratio=NA, log_ratio_std=NA))

for(year_season_host in names(log_ratios_year_season_host_fam)) {
  focal_metadata <- metadata_avg[metadata_avg$hydro_year %in% str_split(year_season_host, "\\_", simplify=T)[,1] & metadata_avg$season %in% str_split(year_season_host, "\\_", simplify=T)[,2] & metadata_avg$host %in% paste(str_split(year_season_host, "\\_", simplify=T)[,3:4], collapse="_"),][,c("sample_id","host","collection_date","hydro_year","season")]
  for(row in 1:nrow(features)) {
    
    log_ratios_year_season_host_fam[[year_season_host]][row,]$log_ratio <- mean(ftbl_avg_clr[focal_metadata$sample_id, features$feature[row]],na.rm=T) - mean(ftbl_avg_clr[, features$feature[row]], na.rm=T)
    log_ratios_year_season_host_fam[[year_season_host]][row,]$log_ratio_std <- std(ftbl_avg_clr[focal_metadata$sample_id, features$feature[row]])-std(ftbl_avg_clr[,features$feature[row]])
  }
}
```

```{r, Fig. 3E, echo=T, eval=T, message=FALSE, warning=FALSE}
# Plot Fig. 3E

# Taxon log-ratios aggregated over time
combine <- bind_rows(
  (log_ratios_host_fam %>% 
     bind_rows(.id="host") %>% 
     group_by(feature) %>% 
     mutate(maxLR=max(abs(log_ratio))) %>% 
     ungroup() %>% 
     mutate(feature=fct_reorder(feature, maxLR, max))),
  (log_ratios_host_phy %>% 
     bind_rows(.id="host") %>% 
     group_by(feature) %>% 
     mutate(maxLR=max(abs(log_ratio))) %>% 
     ungroup() %>% 
     mutate(feature=fct_reorder(feature, maxLR, max)))) 
   
combine %>%  
  ggplot(aes(label=feature)) +
  geom_rect(aes(xmin=as.numeric(feature) - 0.3, xmax=as.numeric(feature) + 0.3, ymin=0, ymax=abs(log_ratio), fill=taxon_level)) +
  geom_point(aes(x=as.numeric(feature), y=abs(log_ratio), color=taxon_level), size=3) +
  coord_flip() +
  geom_hline(yintercept=0, color="black", linetype="dashed") +
  theme_bw() +
  theme(legend.position="none",
        axis.title=element_text(size=16, color="black"),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.background=element_rect(fill="white"),
        panel.border=element_rect(colour="black", fill=NA, size=1),
        axis.ticks.length=unit(0.15,"cm"), 
        axis.text=element_text(size=14, color="black")) +
  scale_fill_manual(values=c("family"="#69e2c5","phylum"="#85cce5")) +
  scale_color_manual(values=c("family"="#06936e","phylum"="#128cad")) +
  labs(x=NULL, y="Log fold change") + 
  scale_x_continuous(label=levels(combine$feature), breaks=1:length(unique(combine$feature)), expand=c(0,0)) +
  scale_y_continuous(expand=c(0.01,0))
```
```{r, Fig. S14, echo=T, eval=T, message=FALSE, warning=FALSE}
# Plot Fig. S14

# Taxon log-ratios for each season and hydrological year
metadata_filtered$hydro_year_season <- paste0(metadata_filtered$hydro_year,"_",metadata_filtered$season)
metadata_filtered$idx <- as.integer(factor(metadata_filtered$hydro_year_season,levels=c("2002_Wet","2002_Dry","2003_Wet","2003_Dry","2004_Wet","2004_Dry","2005_Wet","2005_Dry","2006_Wet","2006_Dry","2007_Wet","2007_Dry","2008_Wet","2008_Dry","2009_Wet","2009_Dry","2010_Wet","2010_Dry")))
rect_idx_season_pad <- cbind(  data.frame(hydro_year=rep(2002:2010, each=2)),
                               data.frame(season=c("Wet","Dry"), stringsAsFactors=F),
                               data.frame(xmin=NA),
                               data.frame(xmax=NA),
                               data.frame(ymin=-Inf),
                               data.frame(ymax=Inf))
rect_idx_season_pad <- rect_idx_season_pad[-nrow(rect_idx_season_pad),]

for(n in 1:nrow(rect_idx_season_pad)) {
  rect_idx_season_pad$xmin[n] <- unique(metadata_filtered[metadata_filtered$hydro_year %in% rect_idx_season_pad$hydro_year[n] & metadata_filtered$season %in% rect_idx_season_pad$season[n],]$idx)
  rect_idx_season_pad$xmax[n] <- unique(metadata_filtered[metadata_filtered$hydro_year %in% rect_idx_season_pad$hydro_year[n] & metadata_filtered$season %in% rect_idx_season_pad$season[n],]$idx+1)
}

rect_idx_season_pad <- cbind(data.frame(hydro_year=rect_idx_season_pad$hydro_year),
                             data.frame(season=rect_idx_season_pad$season),
                             data.frame(xmin=rect_idx_season_pad$xmin),
                             data.frame(xmax=rect_idx_season_pad$xmax),
                             data.frame(ymin=rect_idx_season_pad$ymin),
                             data.frame(ymax=rect_idx_season_pad$ymax))


rect_idx_season_pad$xmin <- rect_idx_season_pad$xmin-1.5
rect_idx_season_pad$xmax <- rect_idx_season_pad$xmax-1.5

x_breaks_season_pad <- rect_idx_season_pad %>% group_by(hydro_year) %>% summarise(min=min(xmin),max=max(xmax))
x_breaks_season_pad$min <- x_breaks_season_pad$min+0.5
x_breaks_season_pad$max <- x_breaks_season_pad$max+0.5

top_6_phy <- log_ratios_host_phy %>% 
    bind_rows(.id="host") %>% 
    group_by(feature) %>% 
    mutate(maxLR=max(abs(log_ratio))) %>% 
    ungroup() %>% 
    mutate(feature=fct_reorder(feature, maxLR, max)) %>% 
    pull(feature) %>% 
    levels() %>% 
    rev() %>% 
    .[1:6]

bottom_6_phy <- log_ratios_host_phy %>% 
    bind_rows(.id="host") %>% 
    group_by(feature) %>% 
    mutate(maxLR=max(abs(log_ratio))) %>% 
    ungroup() %>% 
    mutate(feature=fct_reorder(feature, maxLR, max)) %>% 
    pull(feature) %>% 
    levels() %>% 
    rev() %>% 
    .[7:12]

top_6_fam <- log_ratios_host_fam %>% 
    bind_rows(.id="host") %>% 
    group_by(feature) %>% 
    mutate(maxLR=max(abs(log_ratio))) %>% 
    ungroup() %>% 
    mutate(feature=fct_reorder(feature, maxLR, max)) %>% 
    pull(feature) %>% 
    levels() %>% 
    rev() %>% 
    .[1:6]

bottom_6_fam <- log_ratios_host_fam %>% 
    bind_rows(.id="host") %>% 
    group_by(feature) %>% 
    mutate(maxLR=max(abs(log_ratio))) %>% 
    ungroup() %>% 
    mutate(feature=fct_reorder(feature, maxLR, max)) %>% 
    pull(feature) %>% 
    levels() %>% 
    rev() %>% 
    .[29:34]

# Generate a random color palette for hosts
n <- 56
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'div',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
cols <- sample(col_vector, n)
# pie(rep(1,n), col=cols)
host_cols <- setNames(cols,unique(metadata_filtered$host))

p_top6_phy <- log_ratios_year_season_host_phy %>% 
  bind_rows(.id="id") %>% 
  separate(id, sep=c("\\_"), into=c("hydro_year","Season","host","id")) %>% 
  mutate(host=paste0(host,"_",id),
         feature=fct_reorder(feature, log_ratio, min),
         season=factor(Season, levels=c("Wet","Dry")),
         hydro_year_season=factor(paste0(hydro_year,"_",season), levels=c("2002_Wet","2002_Dry","2003_Wet","2003_Dry","2004_Wet","2004_Dry","2005_Wet","2005_Dry","2006_Wet","2006_Dry","2007_Wet","2007_Dry","2008_Wet","2008_Dry","2009_Wet","2009_Dry","2010_Wet")),
         idx=as.integer(hydro_year_season)-1,
         host=factor(host)) %>% 
  filter(hydro_year %in% 2002:2010) %>% 
  filter(feature %in% top_6_phy) %>%
  mutate(feature=factor(feature, levels=top_6_phy)) %>% 
  ggplot(aes(x=idx, y=log_ratio, color=host)) +
  geom_rect(data=rect_idx_season_pad, inherit.aes=FALSE, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, fill=factor(season)), alpha=0.7, show.legend=F) + 
  scale_fill_manual(values=c("#f6e8c3","#7fbf7b")) +
  geom_errorbar(aes(ymin=log_ratio-log_ratio_std, ymax=log_ratio+log_ratio_std), width=0.3) +
  geom_point(aes(group=host)) +
  geom_line(aes(group=host)) +
  facet_wrap(vars(feature), ncol=2) +
  scale_x_continuous(breaks=x_breaks_season_pad$min, labels=x_breaks_season_pad$hydro_year, expand=c(0,0)) + 
  geom_hline(yintercept=0, color="black", linetype="dashed") +
  theme_bw() +
  theme(legend.position="none",
        strip.background=element_blank(),
        strip.text=element_text(size=12, color="black"),
        axis.text.x=element_text(angle=45, hjust=1, size=10, color="black"),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.background=element_rect(fill="white"),
        panel.border=element_rect(colour="black", fill=NA, size=1),
        axis.ticks.length=unit(0.25,"cm"), 
        axis.text.y=element_text(size=10, color="black"),
        axis.title=element_text(size=12, color="black"),
        plot.title = element_text(hjust=0.5)) +
  scale_color_manual(values=host_cols) +
  labs(y="Log fold change", x="Hydrological year") +
  scale_y_continuous(limits=c(-8, 8)) + 
  labs(title="Top 6 phyla")

p_bottom6_phy <- log_ratios_year_season_host_phy %>% 
  bind_rows(.id="id") %>% 
  separate(id, sep=c("\\_"), into=c("hydro_year","Season","host","id")) %>% 
  mutate(host=paste0(host,"_",id),
         feature=fct_reorder(feature, log_ratio, min),
         season=factor(Season, levels=c("Wet","Dry")),
         hydro_year_season=factor(paste0(hydro_year,"_",season), levels=c("2002_Wet","2002_Dry","2003_Wet","2003_Dry","2004_Wet","2004_Dry","2005_Wet","2005_Dry","2006_Wet","2006_Dry","2007_Wet","2007_Dry","2008_Wet","2008_Dry","2009_Wet","2009_Dry","2010_Wet")),
         idx=as.integer(hydro_year_season)-1,
         host=factor(host)) %>% 
  filter(hydro_year %in% 2002:2010) %>% 
  filter(feature %in% bottom_6_phy) %>%
  mutate(feature=factor(feature, levels=bottom_6_phy)) %>% 
  ggplot(aes(x=idx, y=log_ratio, color=host)) +
  geom_rect(data=rect_idx_season_pad, inherit.aes=FALSE, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, fill=factor(season)), alpha=0.7, show.legend=F) + 
  scale_fill_manual(values=c("#f6e8c3","#7fbf7b")) +
  geom_errorbar(aes(ymin=log_ratio-log_ratio_std, ymax=log_ratio+log_ratio_std), width=0.3) +
  geom_point(aes(group=host)) +
  geom_line(aes(group=host)) +
  facet_wrap(vars(feature), ncol=2) +
  scale_x_continuous(breaks=x_breaks_season_pad$min, labels=x_breaks_season_pad$hydro_year, expand=c(0,0)) + 
  geom_hline(yintercept=0, color="black", linetype="dashed") +
  theme_bw() +
  theme(legend.position="none",
        strip.background=element_blank(),
        strip.text=element_text(size=12, color="black"),
        axis.text.x=element_text(angle=45, hjust=1, size=10, color="black"),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.background=element_rect(fill="white"),
        panel.border=element_rect(colour="black", fill=NA, size=1),
        axis.ticks.length=unit(0.25,"cm"), 
        axis.text.y=element_text(size=10, color="black"),
        axis.title=element_text(size=12, color="black"),
        plot.title = element_text(hjust=0.5)) +
  scale_color_manual(values=host_cols) +
  labs(y="Log fold change", x="Hydrological year") +
  scale_y_continuous(limits=c(-8, 8)) + 
  labs(title="Bottom 6 phyla")

p_top6_phy + p_bottom6_phy

p_top6_fam <- log_ratios_year_season_host_fam %>% 
  bind_rows(.id="id") %>% 
  separate(id, sep=c("\\_"), into=c("hydro_year","Season","host","id")) %>% 
  mutate(host=paste0(host,"_",id),
         feature=fct_reorder(feature, log_ratio, min),
         season=factor(Season, levels=c("Wet","Dry")),
         hydro_year_season=factor(paste0(hydro_year,"_",season), levels=c("2002_Wet","2002_Dry","2003_Wet","2003_Dry","2004_Wet","2004_Dry","2005_Wet","2005_Dry","2006_Wet","2006_Dry","2007_Wet","2007_Dry","2008_Wet","2008_Dry","2009_Wet","2009_Dry","2010_Wet")),
         idx=as.integer(hydro_year_season)-1,
         host=factor(host)) %>% 
  filter(hydro_year %in% 2002:2010) %>% 
  filter(feature %in% top_6_fam) %>%
  mutate(feature=factor(feature, levels=top_6_fam)) %>% 
  ggplot(aes(x=idx, y=log_ratio, color=host)) +
  geom_rect(data=rect_idx_season_pad, inherit.aes=FALSE, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, fill=factor(season)), alpha=0.7, show.legend=F) + 
  scale_fill_manual(values=c("#f6e8c3","#7fbf7b")) +
  geom_errorbar(aes(ymin=log_ratio-log_ratio_std, ymax=log_ratio+log_ratio_std), width=0.3) +
  geom_point(aes(group=host)) +
  geom_line(aes(group=host)) +
  facet_wrap(vars(feature), ncol=2) +
  scale_x_continuous(breaks=x_breaks_season_pad$min, labels=x_breaks_season_pad$hydro_year, expand=c(0,0)) + 
  geom_hline(yintercept=0, color="black", linetype="dashed") +
  theme_bw() +
  theme(legend.position="none",
        strip.background=element_blank(),
        strip.text=element_text(size=12, color="black"),
        axis.text.x=element_text(angle=45, hjust=1, size=10, color="black"),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.background=element_rect(fill="white"),
        panel.border=element_rect(colour="black", fill=NA, size=1),
        axis.ticks.length=unit(0.25,"cm"), 
        axis.text.y=element_text(size=10, color="black"),
        axis.title=element_text(size=12, color="black"),
        plot.title = element_text(hjust=0.5)) +
  scale_color_manual(values=host_cols) +
  labs(y="Log fold change", x="Hydrological year") +
  scale_y_continuous(limits=c(-6, 6)) + 
  labs(title="Top 6 families")

p_bottom6_fam <- log_ratios_year_season_host_fam %>% 
  bind_rows(.id="id") %>% 
  separate(id, sep=c("\\_"), into=c("hydro_year","Season","host","id")) %>% 
  mutate(host=paste0(host,"_",id),
         feature=fct_reorder(feature, log_ratio, min),
         season=factor(Season, levels=c("Wet","Dry")),
         hydro_year_season=factor(paste0(hydro_year,"_",season), levels=c("2002_Wet","2002_Dry","2003_Wet","2003_Dry","2004_Wet","2004_Dry","2005_Wet","2005_Dry","2006_Wet","2006_Dry","2007_Wet","2007_Dry","2008_Wet","2008_Dry","2009_Wet","2009_Dry","2010_Wet")),
         idx=as.integer(hydro_year_season)-1,
         host=factor(host)) %>% 
  filter(hydro_year %in% 2002:2010) %>% 
  filter(feature %in% bottom_6_fam) %>%
  mutate(feature=factor(feature, levels=bottom_6_fam)) %>% 
  ggplot(aes(x=idx, y=log_ratio, color=host)) +
  geom_rect(data=rect_idx_season_pad, inherit.aes=FALSE, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, fill=factor(season)), alpha=0.7, show.legend=F) + 
  scale_fill_manual(values=c("#f6e8c3","#7fbf7b")) +
  geom_errorbar(aes(ymin=log_ratio-log_ratio_std, ymax=log_ratio+log_ratio_std), width=0.3) +
  geom_point(aes(group=host)) +
  geom_line(aes(group=host)) +
  facet_wrap(vars(feature), ncol=2) +
  scale_x_continuous(breaks=x_breaks_season_pad$min, labels=x_breaks_season_pad$hydro_year, expand=c(0,0)) + 
  geom_hline(yintercept=0, color="black", linetype="dashed") +
  theme_bw() +
  theme(legend.position="none",
        strip.background=element_blank(),
        strip.text=element_text(size=12, color="black"),
        axis.text.x=element_text(angle=45, hjust=1, size=10, color="black"),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.background=element_rect(fill="white"),
        panel.border=element_rect(colour="black", fill=NA, size=1),
        axis.ticks.length=unit(0.25,"cm"), 
        axis.text.y=element_text(size=10, color="black"),
        axis.title=element_text(size=12, color="black"),
        plot.title = element_text(hjust=0.5)) +
  scale_color_manual(values=host_cols) +
  labs(y="Log fold change", x="Hydrological year") +
  scale_y_continuous(limits=c(-6, 6)) + 
  labs(title="Bottom 6 families")

p_top6_fam + p_bottom6_fam
```

